Add search query parameters to GLOBALS object
warandoates/g60-love-a-mole pull request #2
Opened 2017-11-14 17:47 UTC by MelisaIm

Added the features for Day 1 requirements

2017-11-14 18:03 UTC, warandoates requested changes
good job so far

2017-11-14 18:03 UTC, warandoates commented on index.html
> +					<input type="number" value="3" name="MOLE_UP_MIN"/>
Why is this indented?

2017-11-14 18:03 UTC, warandoates commented on index.html
>  				<input type="number" value="10" name="NUMBER_OF_ROUNDS"/>
please add id for each input

2017-11-14 18:03 UTC, warandoates commented on index.html
> +				<label>Number Of Rounds</label>
set the for attribute for each input

2017-11-14 18:03 UTC, warandoates commented on javascript/main.js
> +	console.log(GLOBALS);
please remove

2017-11-14 21:39 UTC, MelisaIm commented
Hey Michael, I fixed the bugs you requested.

2017-11-16 16:59 UTC, warandoates approved these changes

2017-11-16 16:59 UTC, merged